version: '2'

services:
  taiga:
    image: mlukman/taiga.io
    container_name: taiga
    restart: always
    environment:
      SITE_URI: http://172.20.103.153:30000
      ADMIN_EMAIL: excode.intra.tm@gmail.com
      TAIGA_DB_HOST: taiga_postgres
      TAIGA_DB_PORT: 5432
      TAIGA_DB_NAME: taiga
      TAIGA_DB_USER: taiga
      TAIGA_DB_PASSWORD: taiga123
    volumes:
      - taiga-media:/opt/taiga/media
      - taiga-static:/opt/taiga/static
    ports:
      - "30000:80"
    networks:
      - taiganet
    depends_on: 
      - taiga_postgres
  taiga_postgres:
    container_name: taiga_postgres
    image: postgres:9.5.6-alpine
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga123
    volumes:
      - taiga-data:/var/lib/postgresql/data
    restart: always
    networks:
      - taiganet
networks:
  taiganet:
  
